name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  meta: ^1.16.0
flutter:
  uses-material-design: true
dev_dependencies:
  mockito: ^5.5.1
  build_runner: ^2.10.1
