name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  # charts_common:
  #   path: ../charts_common/
  flutter:
    sdk: flutter
  charts_common: ^0.12.0
  collection: ^1.19.1
  intl: ^0.17.0
  logging: ^1.3.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  test: ^1.3.0
